services:
  - type: web
    name: flask-api-demo
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: AUTH_MODE
        value: basic
        # value: apikey
      - key: API_KEY
        sync: false
      - key: ADMIN_USER
        value: admin
      - key: ADMIN_PASS
        sync: false
